server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    platform: mysql
    type: org.apache.tomcat.jdbc.pool.DataSource
    dbcp2:
      initial-size: 1
      min-idle: 1
      max-idle: 20
      max-wait-millis: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 20
      validation-query: SELECT x
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INFO/jsp/
      suffix: .jsp
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0
security:
  basic:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: tk.mapper.model
